# Generated by Django 5.0.7 on 2024-07-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20, unique=True)),
                ('product', models.CharField(max_length=50, unique=True)),
                ('can_add_photo', models.BooleanField(default=True)),
                ('vote_as_damaged', models.ImageField(default=1, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
